#!/bin/bash

set -evx

pushd cypress

# Needed to install Cypress plugins
npm install

# Start Cypress tests with docker
docker run -v $PWD:/workdir -w /workdir                     \
    -e CYPRESS_TAGS=$CYPRESS_TAGS                           \
    -e QASE_API_TOKEN=$QASE_API_TOKEN                       \
    -e QASE_REPORT=$QASE_REPORT                             \
    -e QASE_RUN_ID=$QASE_RUN_ID                             \
    -e RANCHER_VERSION=$RANCHER_VERSION                     \
    -e RANCHER_PASSWORD=$RANCHER_PASSWORD                   \
    -e RANCHER_URL=$RANCHER_URL                             \
    -e RANCHER_USER=$RANCHER_USER                           \
    -e GITLAB_PRIVATE_USER=$GITLAB_PRIVATE_USER             \
    -e GITLAB_PRIVATE_PWD=$GITLAB_PRIVATE_PWD               \
    --add-host host.docker.internal:host-gateway            \
    --ipc=host                                              \
    $CYPRESS_DOCKER                                         \
    -s $SPEC
