#!/bin/bash

set -evx

pushd cypress

# Needed to install Cypress plugins
npm install

# Start Cypress tests with docker
docker run -v $PWD:/workdir -w /workdir                     \
    -e CYPRESS_TAGS=$CYPRESS_TAGS                           \
    -e RANCHER_VERSION=$RANCHER_VERSION                     \
    -e RANCHER_PASSWORD=$RANCHER_PASSWORD                   \
    -e RANCHER_URL=$RANCHER_URL                             \
    -e RANCHER_USER=$RANCHER_USER                           \
    --add-host host.docker.internal:host-gateway            \
    --ipc=host                                              \
    $CYPRESS_DOCKER                                         \
    -s $SPEC
